//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiiBalanceWalker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key A")]
        public string ActionLeft {
            get {
                return ((string)(this["ActionLeft"]));
            }
            set {
                this["ActionLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key D")]
        public string ActionRight {
            get {
                return ((string)(this["ActionRight"]));
            }
            set {
                this["ActionRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key W")]
        public string ActionForward {
            get {
                return ((string)(this["ActionForward"]));
            }
            set {
                this["ActionForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key S")]
        public string ActionBackward {
            get {
                return ((string)(this["ActionBackward"]));
            }
            set {
                this["ActionBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key LShiftKey")]
        public string ActionModifier {
            get {
                return ((string)(this["ActionModifier"]));
            }
            set {
                this["ActionModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key Space")]
        public string ActionJump {
            get {
                return ((string)(this["ActionJump"]));
            }
            set {
                this["ActionJump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mouse Move X")]
        public string ActionDiagonalLeft {
            get {
                return ((string)(this["ActionDiagonalLeft"]));
            }
            set {
                this["ActionDiagonalLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mouse Move X")]
        public string ActionDiagonalRight {
            get {
                return ((string)(this["ActionDiagonalRight"]));
            }
            set {
                this["ActionDiagonalRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public int AmountLeft {
            get {
                return ((int)(this["AmountLeft"]));
            }
            set {
                this["AmountLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AmountRight {
            get {
                return ((int)(this["AmountRight"]));
            }
            set {
                this["AmountRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public int AmountForward {
            get {
                return ((int)(this["AmountForward"]));
            }
            set {
                this["AmountForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AmountBackward {
            get {
                return ((int)(this["AmountBackward"]));
            }
            set {
                this["AmountBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AmountModifier {
            get {
                return ((int)(this["AmountModifier"]));
            }
            set {
                this["AmountModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AmountJump {
            get {
                return ((int)(this["AmountJump"]));
            }
            set {
                this["AmountJump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public int AmountDiagonalLeft {
            get {
                return ((int)(this["AmountDiagonalLeft"]));
            }
            set {
                this["AmountDiagonalLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AmountDiagonalRight {
            get {
                return ((int)(this["AmountDiagonalRight"]));
            }
            set {
                this["AmountDiagonalRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int TriggerLeftRight {
            get {
                return ((int)(this["TriggerLeftRight"]));
            }
            set {
                this["TriggerLeftRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int TriggerForwardBackward {
            get {
                return ((int)(this["TriggerForwardBackward"]));
            }
            set {
                this["TriggerForwardBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int TriggerModifierLeftRight {
            get {
                return ((int)(this["TriggerModifierLeftRight"]));
            }
            set {
                this["TriggerModifierLeftRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int TriggerModifierForwardBackward {
            get {
                return ((int)(this["TriggerModifierForwardBackward"]));
            }
            set {
                this["TriggerModifierForwardBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableJoystick {
            get {
                return ((bool)(this["EnableJoystick"]));
            }
            set {
                this["EnableJoystick"] = value;
            }
        }
    }
}
